# Generated by Django 5.2.8 on 2025-11-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_actors_movie_director_movie_trailer_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='mood_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
